'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Tickets.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _220px_Madonna___Madame_X_standard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("220px-Madonna_-_Madame_X_standard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property aboutMadameX() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aboutMadameX", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property AGBookRounded_BoldOutline() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AGBookRounded_BoldOutline", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property AGBookRounded_Medium() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AGBookRounded_Medium", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property AGBookRounded_Medium1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AGBookRounded_Medium1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property AGBookRounded_MediumOutline() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AGBookRounded_MediumOutline", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property AGBookRounded_Regular() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AGBookRounded_Regular", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Confusions_on_a_Dancefloor() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Confusions_on_a_Dancefloor", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property MadameX_ico() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("MadameX_ico", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MadameX_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MadameX_logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MAdamX_logo_Raw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MAdamX_logo_Raw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property madonna_madame_x_tour_dates_tickets_concerts() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("madonna_madame_x_tour_dates_tickets_concerts", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSans_Bold() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSans_Bold", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSans_BoldItalic() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSans_BoldItalic", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSans_Condensed() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSans_Condensed", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSans_CondensedBold() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSans_CondensedBold", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSans_CondensedBoldItalic() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSans_CondensedBoldItalic", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSans_CondensedItalic() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSans_CondensedItalic", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSans_Italic() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSans_Italic", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSans_Light() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSans_Light", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSans_LightItalic() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSans_LightItalic", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSans_Regular() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSans_Regular", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSansLao_Bold() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSansLao_Bold", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSansLao_Regular() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSansLao_Regular", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSansLisu_Regular() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSansLisu_Regular", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSerif_Condensed() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSerif_Condensed", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSerif_CondensedBold() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSerif_CondensedBold", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSerif_CondensedBoldItalic() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSerif_CondensedBoldItalic", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSerif_CondensedItalic() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSerif_CondensedItalic", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSerif_Light() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSerif_Light", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSerif_LightItalic() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSerif_LightItalic", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSerif_Regular() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSerif_Regular", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSerifLao_Bold() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSerifLao_Bold", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSerifLao_Regular() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSerifLao_Regular", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Roboto_Black() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Roboto_Black", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Roboto_BlackItalic() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Roboto_BlackItalic", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Roboto_Bold() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Roboto_Bold", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Roboto_BoldItalic() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Roboto_BoldItalic", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Roboto_ThinItalic() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Roboto_ThinItalic", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rvxX_h9ldzk_QCKYehkgo5D35v8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rvxX_h9ldzk_QCKYehkgo5D35v8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
